# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09da55e96ce499359063fa6d2cad54a88c8a4f866a64bf2f6de19d5f7a20ee892e639fc63c8d687a7d95e719c7811c96190273012c3f1fc00b6f010de8f42723

test:
  secret_key_base: 866d38a9375860eecd9eaf7506b4b6ed386363c1359804e69344c032a2dc040878d3d20eb162105d2105b4b937c7b1a131554739d1216643f88c7c57bb5d4ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
